import { LANGS, LANG_ORDER, availableTargets, getStarterDeck, type LangCode, type Pair } from "./langs";
import { getStrings, LANG_NAMES, type UiStrings } from "./i18n";
import { hashContent } from "./srs";
import { loadAiSettings } from "./aiSettings";
import { fetchSpeech, playBlob } from "./fetchedTts";

export interface Settings {
  pause: number;
  rate: number;
  dir: "EF" | "FE"; // "EF" = native→target prompt direction, "FE" = target→native
  shuffle: boolean;
  loop: boolean;
  showText: boolean;
  mode: "drill" | "test";
  /** The learner's own language — also drives the interface language. */
  nativeLang: LangCode;
  /** The language being drilled. Always different from nativeLang. */
  targetLang: LangCode;
  /** Drill mode only. When false, playback pauses after each card instead of
   *  continuing straight to the next one — for pondering at a screen rather than
   *  hands-free listening (e.g. while driving). */
  autoplay: boolean;
}

export interface EngineSnapshot {
  deck: Pair[];
  order: number[];
  pos: number;
  playing: boolean;
  phaseClass: string;
  phaseLabel: string;
  promptText: string;
  answerText: string;
  revealAnswer: boolean;
  markVisible: boolean;
  summaryVisible: boolean;
  results: boolean[];
  missedCount: number;
  settings: Settings;
  deckLabel: string;
  status: string;
  statusErr: boolean;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

/**
 * Faithful port of repetez.html's playback engine. Kept as a plain, framework-agnostic
 * class (not hooks) on purpose: the original's async-loop-guard pattern — every `await`
 * inside runFrom() followed by a `playing`/`runToken` check — is the load-bearing bit that
 * prevents ghost audio after skip/stop, and a straight port is far lower-risk than
 * re-deriving the same behaviour as idiomatic hooks. React subscribes via
 * useSyncExternalStore (see components/repeatafterme/Player.tsx); the engine has no
 * knowledge of React.
 *
 * Thinking-bar animation and wake-lock/audio-session plumbing stay imperative (callbacks
 * set by the consumer) rather than snapshot fields, matching the original's direct style
 * manipulation — re-rendering React for a CSS transition would be the wrong tool.
 *
 * i18n: `this.t` holds the UI strings dictionary for the current nativeLang, re-derived
 * whenever nativeLang changes (setNativeLang, hydrate, loadSavedDeck). Any English literal
 * generated by this class (phase labels, status messages) must go through `this.t`, never
 * a hardcoded string — that's what makes the interface follow the learner's native language.
 */
export class RepetezEngine {
  private deck: Pair[];
  private order: number[] = [];
  private pos = 0;
  private playing = false;
  private playStartedAt: number | null = null;
  private runToken = 0;
  private settings: Settings;
  private t: UiStrings;
  private results: boolean[] = [];
  private missed: number[] = [];
  private markResolve: ((v: boolean | null) => void) | null = null;
  private wakeLock: WakeLockSentinel | null = null;
  private voices: SpeechSynthesisVoice[] = [];
  private audioCtx: AudioContext | null = null;
  /** In-flight fetched-audio TTS element (see speak()) — tracked so stop()/next()/
   *  prev()/repeatCurrent() can interrupt it the same way they cancel Web Speech. */
  private activeAudio: HTMLAudioElement | null = null;

  private phaseClass = "";
  private phaseLabel: string;
  private promptText: string;
  private answerText = "";
  private revealAnswer = false;
  private markVisible = false;
  private summaryVisible = false;
  private deckLabel: string;
  private status = "";
  private statusErr = false;

  /** Set only while playing a due-today queue (loadDueQueue) — maps each deck index to
   *  the item's real itemKey from wherever it originally came from, so marking it feeds
   *  SRS back to the right underlying item rather than a fresh hash of this ephemeral
   *  aggregated "deck". null for a normal single-source deck, where the itemKey is
   *  derived on the fly from a content hash (see markReviewed()). */
  private itemKeyOverride: string[] | null = null;

  private listeners = new Set<() => void>();
  private snapshot: EngineSnapshot;

  onThinkStart: ((ms: number) => void) | null = null;
  onThinkStop: (() => void) | null = null;
  /** Fired whenever settings or the active deck change — the consumer's cue to persist. */
  onDeckOrSettingsChange: (() => void) | null = null;
  /** Fired when a test run finishes — the consumer's cue to record score history. */
  onTestComplete: ((result: { deckLabel: string; targetLang: LangCode; correct: number; total: number }) => void) | null = null;
  /** Fired whenever a play→stop cycle ends, with elapsed seconds — the consumer's cue
   *  to log session-stats activity (streak, minutes practised). */
  onSessionTime: ((seconds: number) => void) | null = null;
  /** Fired on every Test-mode mark — the consumer's cue to update spaced-repetition state. */
  onItemReviewed: ((info: { itemKey: string; deckLabel: string; nativeLang: LangCode; targetLang: LangCode; pair: Pair; correct: boolean }) => void) | null = null;
  /** Fired whenever the current card settles on a new item (not just revealing the
   *  answer for the same one) — with the stable deck-item index (order[pos]), not the
   *  raw position, so it stays meaningful across shuffle changes. Consumer's cue to
   *  persist "resume where I left off". */
  onPositionChange: ((deckIndex: number) => void) | null = null;

  constructor(nativeLang: LangCode = "en", targetLang?: LangCode) {
    const target = targetLang ?? availableTargets(nativeLang)[0];
    this.settings = { pause: 1.25, rate: 0.9, dir: "EF", shuffle: false, loop: true, showText: true, mode: "drill", nativeLang, targetLang: target, autoplay: true };
    this.t = getStrings(nativeLang);
    this.deck = getStarterDeck(nativeLang, target);
    this.deckLabel = this.t.starterDeck(this.deck.length);
    this.phaseLabel = this.t.phaseReady;
    this.promptText = this.t.promptPressPlay;
    this.rebuildOrder();
    this.syncCard(false);
    this.snapshot = this.buildSnapshot();
  }

  // ---------- subscription (useSyncExternalStore contract) ----------
  subscribe = (fn: () => void) => {
    this.listeners.add(fn);
    return () => this.listeners.delete(fn);
  };
  getSnapshot = (): EngineSnapshot => this.snapshot;

  private buildSnapshot(): EngineSnapshot {
    return {
      deck: this.deck,
      order: this.order,
      pos: this.pos,
      playing: this.playing,
      phaseClass: this.phaseClass,
      phaseLabel: this.phaseLabel,
      promptText: this.promptText,
      answerText: this.answerText,
      revealAnswer: this.revealAnswer,
      markVisible: this.markVisible,
      summaryVisible: this.summaryVisible,
      results: this.results,
      missedCount: this.missed.length,
      settings: this.settings,
      deckLabel: this.deckLabel,
      status: this.status,
      statusErr: this.statusErr,
    };
  }

  private emit() {
    this.snapshot = this.buildSnapshot();
    this.listeners.forEach((fn) => fn());
  }

  // ---------- voices (call once client-side, e.g. from a useEffect) ----------
  setVoices(voices: SpeechSynthesisVoice[]) {
    this.voices = voices;
  }

  private pickVoice(which: "native" | "target"): SpeechSynthesisVoice | null {
    const langCode = which === "native" ? this.settings.nativeLang : this.settings.targetLang;
    const pref = this.voices.filter((v) => v.lang && v.lang.toLowerCase().startsWith(langCode));
    if (!pref.length) return null;
    const preferred = LANGS[langCode].voiceNames.concat(["google"]);
    for (const name of preferred) {
      const hit = pref.find((v) => v.name.toLowerCase().includes(name));
      if (hit) return hit;
    }
    return pref[0];
  }

  /** Fetched OpenAI audio when the configured AI provider is OpenAI (same BYOK key
   *  used for deck generation — see aiSettings.ts), falling back to Web Speech
   *  otherwise or if the fetch fails. Same reasoning as Écoutez's identical pattern
   *  (fetchedTts.ts): <audio> elements route over Bluetooth reliably and survive
   *  screen lock, unlike Web Speech. `which` only matters for the Web Speech path —
   *  OpenAI's TTS auto-detects language from the text itself. */
  private async speak(text: string, which: "native" | "target"): Promise<void> {
    const ai = loadAiSettings();
    if (ai.provider === "openai" && ai.apiKey.trim()) {
      try {
        const blob = await fetchSpeech(text, ai.apiKey, this.settings.rate);
        await playBlob(blob, (audio) => (this.activeAudio = audio));
        this.activeAudio = null;
        return;
      } catch {
        // fall through to Web Speech
      }
    }
    return new Promise((resolve) => {
      if (typeof window === "undefined" || !window.speechSynthesis) return resolve();
      const u = new SpeechSynthesisUtterance(text);
      u.lang = LANGS[which === "native" ? this.settings.nativeLang : this.settings.targetLang].tts;
      const v = this.pickVoice(which);
      if (v) u.voice = v;
      u.rate = this.settings.rate;
      u.onend = () => resolve();
      u.onerror = () => resolve();
      window.speechSynthesis.speak(u);
    });
  }

  // ---------- audio session keep-alive (Bluetooth routing fix) ----------
  private ensureAudioSession() {
    try {
      if (!this.audioCtx) {
        const AC = window.AudioContext || (window as unknown as { webkitAudioContext?: typeof AudioContext }).webkitAudioContext;
        if (!AC) return;
        this.audioCtx = new AC();
        const osc = this.audioCtx.createOscillator();
        const gain = this.audioCtx.createGain();
        gain.gain.value = 0.001;
        osc.frequency.value = 30;
        osc.connect(gain).connect(this.audioCtx.destination);
        osc.start();
      }
      if (this.audioCtx.state === "suspended") this.audioCtx.resume();
    } catch {
      /* no-op — best-effort Bluetooth routing nudge */
    }
  }
  private pauseAudioSession() {
    try {
      this.audioCtx?.suspend();
    } catch {
      /* no-op */
    }
  }

  private async requestWake() {
    try {
      if ("wakeLock" in navigator) this.wakeLock = await navigator.wakeLock.request("screen");
    } catch {
      /* no-op — wake lock is best-effort */
    }
  }
  private releaseWake() {
    try {
      this.wakeLock?.release();
    } catch {
      /* no-op */
    }
    this.wakeLock = null;
  }
  reacquireWakeIfPlaying() {
    if (this.playing) void this.requestWake();
  }

  // ---------- order / card display ----------
  private rebuildOrder() {
    this.order = this.deck.map((_, i) => i);
    if (this.settings.shuffle) {
      for (let i = this.order.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [this.order[i], this.order[j]] = [this.order[j], this.order[i]];
      }
    }
  }

  private setPhase(cls: string, label: string) {
    this.phaseClass = cls;
    this.phaseLabel = label;
  }

  private syncCard(revealAnswer: boolean) {
    const [native, target] = this.deck[this.order[this.pos]];
    const prompt = this.settings.dir === "EF" ? native : target;
    const answer = this.settings.dir === "EF" ? target : native;
    this.promptText = this.settings.showText ? prompt : "🎧";
    this.answerText = answer;
    this.revealAnswer = revealAnswer && this.settings.showText;
  }

  // ---------- player loop ----------
  private async runFrom(startPos: number) {
    const token = ++this.runToken;
    this.pos = startPos;
    while (this.playing && token === this.runToken) {
      const [native, target] = this.deck[this.order[this.pos]];
      const prompt = this.settings.dir === "EF" ? native : target;
      const answer = this.settings.dir === "EF" ? target : native;
      const promptLang: "native" | "target" = this.settings.dir === "EF" ? "native" : "target";
      const answerLang: "native" | "target" = this.settings.dir === "EF" ? "target" : "native";

      this.syncCard(false);
      this.setPhase("speaking", this.t.phaseListen);
      this.emit();
      await this.speak(prompt, promptLang);
      if (!this.playing || token !== this.runToken) break;

      const ms = Math.max(2200, answer.length * 90 * this.settings.pause);
      const answerLangCode = answerLang === "target" ? this.settings.targetLang : this.settings.nativeLang;
      this.setPhase("yourturn", this.t.phaseYourTurn(LANG_NAMES[this.settings.nativeLang][answerLangCode]));
      this.emit();
      this.onThinkStart?.(ms);
      await sleep(ms);
      this.onThinkStop?.();
      if (!this.playing || token !== this.runToken) break;

      this.syncCard(true);
      this.setPhase("speaking", this.t.phaseAnswer);
      this.emit();
      await this.speak(answer, answerLang);
      if (!this.playing || token !== this.runToken) break;

      if (this.settings.mode === "test") {
        this.setPhase("yourturn", this.t.phaseDidYouGetIt);
        this.markVisible = true;
        this.emit();
        const ok = await new Promise<boolean | null>((res) => {
          this.markResolve = res;
        });
        this.markVisible = false;
        if (ok === null || !this.playing || token !== this.runToken) {
          this.emit();
          break;
        }
        this.results.push(ok);
        if (!ok) this.missed.push(this.order[this.pos]);
        this.emit();
        this.markReviewed(this.order[this.pos], ok);
        // Breathing room after the mark click — without this, the next prompt's
        // audio started essentially instantly on tap, which felt jarring.
        await sleep(700);
        if (!this.playing || token !== this.runToken) break;
      } else {
        await sleep(900);
        if (!this.playing || token !== this.runToken) break;
      }

      if (this.pos + 1 >= this.order.length) {
        if (this.settings.mode === "test") {
          this.finishTest();
          return;
        }
        if (this.settings.loop) {
          if (this.settings.shuffle) this.rebuildOrder();
          this.pos = 0;
        } else {
          this.stop();
          this.setPhase("", this.t.phaseDeckComplete);
          this.emit();
          return;
        }
      } else {
        this.pos++;
      }
      this.notePosition();

      // Drill mode, autoplay off: pause here rather than continuing straight into
      // the next card. `pos` is already advanced, so a subsequent play() picks up
      // the next card — not a repeat of the one just finished. Wake lock is left
      // alone deliberately: this is an expected step in the flow (pondering at a
      // screen), not the user walking away, so the screen should stay awake.
      if (this.settings.mode === "drill" && !this.settings.autoplay) {
        this.playing = false;
        this.recordSessionTime();
        this.syncCard(false);
        this.setPhase("", this.t.phaseReadyNextCard);
        this.emit();
        return;
      }
    }
  }

  private resetTest() {
    this.results = [];
    this.missed = [];
    this.summaryVisible = false;
    this.markVisible = false;
  }

  private notePosition() {
    if (this.order.length) this.onPositionChange?.(this.order[this.pos]);
  }

  /** itemKey is either resolved from itemKeyOverride (due-queue: item came from
   *  elsewhere, keep its real identity) or derived on the fly from a content hash of
   *  the current deck (normal deck: cheap enough to recompute per mark, and avoids a
   *  cached field ever going stale after a deck reload). */
  private markReviewed(deckIndex: number, correct: boolean) {
    const itemKey = this.itemKeyOverride ? this.itemKeyOverride[deckIndex] : `${hashContent(this.deck)}:${deckIndex}`;
    this.onItemReviewed?.({
      itemKey,
      deckLabel: this.deckLabel,
      nativeLang: this.settings.nativeLang,
      targetLang: this.settings.targetLang,
      pair: this.deck[deckIndex],
      correct,
    });
  }

  /** Called from every path that transitions playing→not-playing (stop() and
   *  finishTest(), which doesn't route through stop()) — reports real elapsed time
   *  for session stats, ignoring negligible durations (e.g. an immediate re-pause). */
  private recordSessionTime() {
    if (this.playStartedAt === null) return;
    const elapsed = (Date.now() - this.playStartedAt) / 1000;
    this.playStartedAt = null;
    if (elapsed > 0.5) this.onSessionTime?.(elapsed);
  }

  private finishTest() {
    this.playing = false;
    this.runToken++;
    this.releaseWake();
    this.recordSessionTime();
    const good = this.results.filter(Boolean).length;
    this.setPhase("", this.t.phaseTestComplete);
    this.promptText = this.t.correctOutOf(good, this.results.length);
    this.answerText = "";
    this.revealAnswer = false;
    this.summaryVisible = true;
    this.emit();
    this.onTestComplete?.({ deckLabel: this.deckLabel, targetLang: this.settings.targetLang, correct: good, total: this.results.length });
  }

  // ---------- transport ----------
  play() {
    if (!this.deck.length) return;
    this.ensureAudioSession();
    if (this.settings.mode === "test" && this.pos === 0 && !this.results.length) this.resetTest();
    this.summaryVisible = false;
    this.playing = true;
    this.playStartedAt = Date.now();
    void this.requestWake();
    this.emit();
    void this.runFrom(this.pos);
  }

  stop() {
    this.playing = false;
    this.runToken++;
    this.recordSessionTime();
    if (this.markResolve) {
      const r = this.markResolve;
      this.markResolve = null;
      r(null);
    }
    this.markVisible = false;
    if (typeof window !== "undefined") window.speechSynthesis?.cancel();
    this.activeAudio?.pause();
    this.onThinkStop?.();
    this.setPhase("", this.t.phasePaused);
    this.pauseAudioSession();
    this.releaseWake();
    this.emit();
  }

  toggle() {
    if (this.playing) this.stop();
    else this.play();
  }

  next() {
    if (typeof window !== "undefined") window.speechSynthesis?.cancel();
    this.activeAudio?.pause();
    this.pos = (this.pos + 1) % this.order.length;
    this.notePosition();
    if (this.playing) void this.runFrom(this.pos);
    else {
      this.syncCard(false);
      this.emit();
    }
  }

  prev() {
    if (typeof window !== "undefined") window.speechSynthesis?.cancel();
    this.activeAudio?.pause();
    this.pos = (this.pos - 1 + this.order.length) % this.order.length;
    this.notePosition();
    if (this.playing) void this.runFrom(this.pos);
    else {
      this.syncCard(false);
      this.emit();
    }
  }

  repeatCurrent() {
    if (typeof window !== "undefined") window.speechSynthesis?.cancel();
    this.activeAudio?.pause();
    if (this.playing) void this.runFrom(this.pos);
    else {
      this.playing = true;
      this.emit();
      void this.runFrom(this.pos);
    }
  }

  /** The stable identity of the current card (order[pos]) — unaffected by shuffle
   *  re-randomising `order` itself. Used by the consumer for "bookmark this spot". */
  getCurrentDeckIndex(): number {
    return this.order[this.pos];
  }

  /** Jump to the Nth card (1-indexed, matching the on-screen counter) in the
   *  *current* play order. Drill mode only — Test mode's scoring assumes sequential
   *  completion, so jumping around mid-test would leave results/missed inconsistent.
   *  With shuffle on, "card N" is only a stable target until the next reshuffle. */
  goToPosition(n: number) {
    if (this.settings.mode !== "drill" || !this.order.length) return;
    this.stop();
    this.pos = Math.min(Math.max(0, Math.trunc(n) - 1), this.order.length - 1);
    this.syncCard(false);
    this.setPhase("", this.t.phaseReady);
    this.emit();
    this.notePosition();
  }

  /** Jump to a specific underlying card by its stable deck-item identity — used to
   *  restore a bookmark. Correct regardless of shuffle state, unlike goToPosition().
   *  No-ops quietly if the index isn't in the current order (e.g. deck shrank). */
  goToDeckIndex(deckIndex: number) {
    if (this.settings.mode !== "drill") return;
    const idx = this.order.indexOf(deckIndex);
    if (idx < 0) return;
    this.stop();
    this.pos = idx;
    this.syncCard(false);
    this.setPhase("", this.t.phaseReady);
    this.emit();
    this.notePosition();
  }

  // ---------- test marking ----------
  markKnew() {
    if (this.markResolve) {
      const r = this.markResolve;
      this.markResolve = null;
      r(true);
    }
  }
  markMissed() {
    if (this.markResolve) {
      const r = this.markResolve;
      this.markResolve = null;
      r(false);
    }
  }
  practiseMisses() {
    this.order = this.missed.slice();
    this.pos = 0;
    this.resetTest();
    this.play();
  }
  restartTest() {
    this.rebuildOrder();
    this.pos = 0;
    this.resetTest();
    this.play();
  }

  // ---------- settings ----------
  setPause(v: number) {
    this.settings.pause = v;
    this.emit();
    this.onDeckOrSettingsChange?.();
  }
  setRate(v: number) {
    this.settings.rate = v;
    this.emit();
    this.onDeckOrSettingsChange?.();
  }
  setDir(dir: "EF" | "FE") {
    this.settings.dir = dir;
    this.syncCard(false);
    this.emit();
    this.onDeckOrSettingsChange?.();
  }
  setMode(mode: "drill" | "test") {
    this.stop();
    this.settings.mode = mode;
    this.resetTest();
    this.rebuildOrder();
    this.pos = 0;
    this.syncCard(false);
    if (mode === "test") this.setPhase("", this.t.phaseTestReady);
    this.emit();
    this.onDeckOrSettingsChange?.();
  }
  /** Switch the language being drilled. Resets to that pairing's starter deck —
   *  existing deck content is tied to the old pairing and wouldn't make sense to keep. */
  setTargetLang(code: LangCode) {
    if (code === this.settings.nativeLang) return; // never allow native === target
    this.stop();
    this.settings.targetLang = code;
    this.loadStarterFor(this.settings.nativeLang, code);
  }
  /** Switch the learner's native language — also flips the interface language (this.t)
   *  and, if the current target is no longer valid (target === new native), picks the
   *  first remaining available target. Resets to that pairing's starter deck. */
  setNativeLang(code: LangCode) {
    this.stop();
    this.settings.nativeLang = code;
    this.t = getStrings(code);
    const targets = availableTargets(code);
    if (!targets.includes(this.settings.targetLang)) {
      this.settings.targetLang = targets[0];
    }
    this.loadStarterFor(code, this.settings.targetLang);
  }
  private loadStarterFor(native: LangCode, target: LangCode) {
    this.itemKeyOverride = null;
    this.deck = getStarterDeck(native, target);
    this.pos = 0;
    this.rebuildOrder();
    this.resetTest();
    this.syncCard(false);
    this.deckLabel = this.t.starterDeck(this.deck.length);
    this.status = this.t.statusSwitchedTarget(LANG_NAMES[native][target]);
    this.statusErr = false;
    this.emit();
    this.onDeckOrSettingsChange?.();
  }
  toggleShuffle() {
    this.settings.shuffle = !this.settings.shuffle;
    this.rebuildOrder();
    this.pos = 0;
    this.syncCard(false);
    this.emit();
    this.onDeckOrSettingsChange?.();
  }
  toggleLoop() {
    this.settings.loop = !this.settings.loop;
    this.emit();
    this.onDeckOrSettingsChange?.();
  }
  toggleShowText() {
    this.settings.showText = !this.settings.showText;
    this.syncCard(this.revealAnswer);
    this.emit();
    this.onDeckOrSettingsChange?.();
  }
  toggleAutoplay() {
    this.settings.autoplay = !this.settings.autoplay;
    this.emit();
    this.onDeckOrSettingsChange?.();
  }

  // ---------- deck loading ----------
  loadDeck(rows: Pair[], label: string, opts: { silent?: boolean } = {}) {
    if (!rows.length) {
      this.status = this.t.statusNoPhrasesFound;
      this.statusErr = true;
      this.emit();
      return;
    }
    this.stop();
    this.itemKeyOverride = null;
    this.deck = rows;
    this.pos = 0;
    this.rebuildOrder();
    this.resetTest();
    this.syncCard(false);
    this.deckLabel = this.t.deckPhrases(label, this.deck.length);
    if (!opts.silent) {
      this.status = this.t.statusLoadedPhrases(this.deck.length);
      this.statusErr = false;
    }
    this.emit();
    if (!opts.silent) this.onDeckOrSettingsChange?.();
  }

  /** Restore persisted settings + last-used deck (+ position, if it matches this
   *  deck's content — see db.ts's getLastPosition) on mount. Silent — no status
   *  message, no onDeckOrSettingsChange/onPositionChange echo (we're loading what was
   *  already saved, not changing it). */
  hydrate(opts: { settings?: Partial<Settings>; deck?: { pairs: Pair[]; label: string }; deckIndex?: number }) {
    this.itemKeyOverride = null;
    if (opts.settings) this.settings = { ...this.settings, ...opts.settings };
    this.t = getStrings(this.settings.nativeLang);
    if (opts.deck?.pairs.length) {
      this.deck = opts.deck.pairs;
      this.deckLabel = opts.deck.label;
    } else {
      this.deck = getStarterDeck(this.settings.nativeLang, this.settings.targetLang);
      this.deckLabel = this.t.starterDeck(this.deck.length);
    }
    this.pos = 0;
    this.rebuildOrder();
    if (opts.deckIndex !== undefined) {
      const idx = this.order.indexOf(opts.deckIndex);
      if (idx >= 0) this.pos = idx;
    }
    this.resetTest();
    this.syncCard(false);
    this.emit();
  }

  /** Load a saved deck, switching native+target language first if it was saved under a
   *  different pairing (so TTS uses the right voices and the UI translates correctly) —
   *  used by the deck library's "Load". */
  loadSavedDeck(pairs: Pair[], label: string, nativeLang: LangCode, targetLang: LangCode) {
    if (nativeLang !== this.settings.nativeLang) {
      this.settings.nativeLang = nativeLang;
      this.t = getStrings(nativeLang);
    }
    if (targetLang !== this.settings.targetLang) this.settings.targetLang = targetLang;
    this.loadDeck(pairs, label);
  }

  /** Load an aggregated queue of due SRS items (from db.ts's listDueSrsRecords) as the
   *  active deck, in Test mode, remembering each item's real itemKey so marking it
   *  updates the right underlying item rather than being treated as new content.
   *  Scoped to items already matching the current native/target pairing — see
   *  db.ts's listDueSrsRecords for why mixed-pairing queues aren't supported. */
  loadDueQueue(items: { itemKey: string; pair: Pair }[], label: string) {
    if (!items.length) return;
    this.stop();
    this.settings.mode = "test";
    this.itemKeyOverride = items.map((i) => i.itemKey);
    this.deck = items.map((i) => i.pair);
    this.pos = 0;
    this.rebuildOrder();
    this.resetTest();
    this.syncCard(false);
    this.deckLabel = label;
    this.setPhase("", this.t.phaseTestReady);
    this.status = "";
    this.statusErr = false;
    this.emit();
    this.onDeckOrSettingsChange?.();
  }

  /** Current deck's content, for the consumer to persist (last-used or save-to-library). */
  getCurrentDeck(): { pairs: Pair[]; label: string; nativeLang: LangCode; targetLang: LangCode } {
    // Strip any " · N phrases" suffix so re-saving doesn't accumulate labels.
    const label = this.deckLabel.replace(/\s*·\s*\d+\s*(phrases|frases)$/i, "");
    return { pairs: this.deck, label, nativeLang: this.settings.nativeLang, targetLang: this.settings.targetLang };
  }

  setStatus(msg: string, err = false) {
    this.status = msg;
    this.statusErr = err;
    this.emit();
  }
}

export { LANG_ORDER, availableTargets };
